const express = require('express')
const path = require('path')
const app = express()
const home = require('./route/home')
const admin = require('./route/admin')
//开放所有静态文件
app.use(express.static(path.join(__dirname,'public')))
app.use('/home',home)
app.use('/admin',admin)
app.listen(3000)
console.log('服务器启动成功')